@ECHO OFF
ECHO SIMPLE BATTERY REPORT / TEST (C) CARL HOPKINS 2022
ECHO.
ECHO HTML REPORT WILL BE GENERATED IN THE SAME LOCATION AS THIS FILE
PAUSE
powercfg /batteryreport /output "batteryreport.html"
ECHO REPORT COMPLETE
TIMEOUT 5 > NUL
EXIT /b